name: PHP TESTS

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: RUN TESTS
    steps:
      - uses: actions/checkout@v1
      # For YAML Actions, use v1 or later
      - run: composer install
      - run: ./vendor/bin/phpunit tests/QueryTest.php
  phpinsights:
        needs: phpunit
        runs-on: ubuntu-latest
        name: RUN CHECK INSIGHTS
        steps:
          - uses: actions/checkout@v2
          - uses: shivammathur/setup-php@v1
            with:
                php-version: 8.0.0
          - run: composer install --prefer-dist --no-progress --no-suggest
          - run: vendor/bin/phpinsights --no-interaction --disable-security-check
  deploy:
    needs: [phpunit, phpinsights]
    runs-on: ubuntu-latest
    name: DEPLOY APP
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: RUN DEPLOY FILE
        run: ./deploy.sh
